### ISSUE TITLE
Add automatically disabling of snapshotting in genetic mode

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles#11]
Need to disable snapshotting in genetic mode because large number of snapshots is overflowing memory.

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/54/1)
for change [54](https://velesnet.ml/gerrit/#/c/54) which triggered build [2215](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2215/)

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/54/1)
for change [54](https://velesnet.ml/gerrit/#/c/54) which triggered build [2216](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2216/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/98/1)
for change [98](https://velesnet.ml/gerrit/#/c/98) which triggered build [2239](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2239/)
