### ISSUE TITLE
Improve garbage collection in tests

### ISSUE THREAD

**Issue by ajkxyz** [Samsung/veles#19]

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/55/1)
for change [55](https://velesnet.ml/gerrit/#/c/55) which triggered build [2217](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2217/)

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/55/1)
for change [55](https://velesnet.ml/gerrit/#/c/55) which triggered build [2218](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2218/)

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/55/1)
for change [55](https://velesnet.ml/gerrit/#/c/55) which triggered build [2219](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2219/)

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/55/1)
for change [55](https://velesnet.ml/gerrit/#/c/55) which triggered build [2220](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2220/)

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/55/1)
for change [55](https://velesnet.ml/gerrit/#/c/55) which triggered build [2221](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2221/)

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/55/1)
for change [55](https://velesnet.ml/gerrit/#/c/55) which triggered build [2222](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2222/)
