### ISSUE TITLE
Fix forward extraction. Add forward extraction example

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles#20]
https://github.com/Samsung/veles.znicz/issues/15

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/70/1)
for change [70](https://velesnet.ml/gerrit/#/c/70) which triggered build [2226](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2226/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/71/1)
for change [71](https://velesnet.ml/gerrit/#/c/71) which triggered build [2227](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2227/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/70/2)
for change [70](https://velesnet.ml/gerrit/#/c/70) which triggered build [2228](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2228/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [4](https://velesnet.ml/gerrit/#/c/70/4)
for change [70](https://velesnet.ml/gerrit/#/c/70) which triggered build [2230](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2230/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/99/1)
for change [99](https://velesnet.ml/gerrit/#/c/99) which triggered build [2240](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2240/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/100/1)
for change [100](https://velesnet.ml/gerrit/#/c/100) which triggered build [2241](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2241/)
