### ISSUE TITLE
Fix tests for 0.8.2 release #10

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles#23]
https://github.com/Samsung/veles.znicz/issues/10

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/107/1)
for change [107](https://velesnet.ml/gerrit/#/c/107) which triggered build [2242](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2242/)
