### ISSUE TITLE
Fix automatically downloading of files. Set correct paths for data

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles#26]
https://github.com/Samsung/veles.znicz/issues/19

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/116/1)
for change [116](https://velesnet.ml/gerrit/#/c/116) which triggered build [2246](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2246/)
