### ISSUE TITLE
Refactor InputJoiner

### ISSUE THREAD

**Issue by ajkxyz** [Samsung/veles#4]
Add link_inputs method to InputJoiner class, add input_0, input_1, ..., offset_0, offset_1, ..., length_0, length_1, ... properties for each of the input.

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [2](https://velesnet.ml/gerrit/#/c/11/2)
for change [11](https://velesnet.ml/gerrit/#/c/11) which triggered build [2188](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2188/)

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/86/1)
for change [86](https://velesnet.ml/gerrit/#/c/86) which triggered build [2233](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2233/)
