### ISSUE TITLE
Add Imagenet forward propagation

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles#47]
https://github.com/Samsung/veles.znicz/issues/35

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/225/1)
for change [225](https://velesnet.ml/gerrit/#/c/225) which triggered build [2297](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2297/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/230/1)
for change [230](https://velesnet.ml/gerrit/#/c/230) which triggered build [2298](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2298/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/233/1)
for change [233](https://velesnet.ml/gerrit/#/c/233) which triggered build [2300](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2300/)
