### ISSUE TITLE
What happened after 2016?

### ISSUE THREAD

**Issue by kamathln** [Samsung/veles#52]
Is it still in development? Are there any active forks?

**Comment by somang-park** [comment]
sorry, I think the managers of source code have gone out from this projects. :(

**Comment by somang-park** [comment]
We are currently developing on the other side. We do not have the capacity to contribute. We hope, you can contribute code for this project. Thanks

**Comment by Nashev** [comment]
Do You know any similar open source projects which are not abandoned today?

**Comment by somang-park** [comment]
Um... Actually, as the core technologies are emerging every year, developers are moving to new project or new core technologies, so I can't check it right now unfortunately.
