### ISSUE TITLE
Fix incorrect LinkableAttribute behaviour when attribute already contained in object's __dict__

### ISSUE THREAD

**Issue by ajkxyz** [Samsung/veles#6]

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/32/1)
for change [32](https://velesnet.ml/gerrit/#/c/32) which triggered build [2205](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2205/)
