### ISSUE TITLE
Fix manhole option

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles#7]
When manhole is closing, spinner tries to write in closed stdout

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/33/1)
for change [33](https://velesnet.ml/gerrit/#/c/33) which triggered build [2206](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2206/)
