### ISSUE TITLE
Add logging info in Snapshotter

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles#8]
Need to add logging info when Snapshotter is reading files

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/34/1)
for change [34](https://velesnet.ml/gerrit/#/c/34) which triggered build [2207](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2207/)
